platform :ios, '8.0'

target :PinDuoDuoTest do
 lspod 'SDWebImage', '~> 3.7.3’
 pod 'AFNetworking', '~> 3.0.0-beta.1'
 pod 'MJRefresh', '~> 2.4.12'

 pod 'MBProgressHUD', '~> 0.9.1'
 pod 'Masonry', '~> 0.6.3'
 pod 'SDCycleScrollView', '~> 1.3'
end